//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace GablarskiGtk
{
	public partial class ConnectWindow : Gtk.Window
	{		
		public ConnectWindow () : base(Gtk.WindowType.Toplevel)
		{
			Build();
		}
	}
}