//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GablarskiGtk {
    
    
    public partial class ConnectWindow {
        
        private Gtk.Fixed serverPane;
        
        private Gtk.Label lblServer;
        
        private Gtk.Entry nickname;
        
        private Gtk.Button cancelButton;
        
        private Gtk.Button okButton;
        
        private Gtk.Entry server;
        
        private Gtk.Entry port;
        
        private Gtk.Label lblNickname;
        
        private Gtk.Label lblPort;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GablarskiGtk.ConnectWindow
            this.Name = "GablarskiGtk.ConnectWindow";
            this.Title = Mono.Unix.Catalog.GetString("Connect");
            this.Icon = Gdk.Pixbuf.LoadFromResource("GablarskiGtk.server_connect.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.SkipTaskbarHint = true;
            // Container child GablarskiGtk.ConnectWindow.Gtk.Container+ContainerChild
            this.serverPane = new Gtk.Fixed();
            this.serverPane.Name = "serverPane";
            this.serverPane.HasWindow = false;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.lblServer = new Gtk.Label();
            this.lblServer.Name = "lblServer";
            this.lblServer.LabelProp = Mono.Unix.Catalog.GetString("Server:");
            this.serverPane.Add(this.lblServer);
            Gtk.Fixed.FixedChild w1 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.lblServer]));
            w1.X = 20;
            w1.Y = 15;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.nickname = new Gtk.Entry();
            this.nickname.CanFocus = true;
            this.nickname.Name = "nickname";
            this.nickname.IsEditable = true;
            this.serverPane.Add(this.nickname);
            Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.nickname]));
            w2.X = 115;
            w2.Y = 85;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.cancelButton = new Gtk.Button();
            this.cancelButton.CanFocus = true;
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.UseUnderline = true;
            this.cancelButton.Label = Mono.Unix.Catalog.GetString("Cancel");
            this.serverPane.Add(this.cancelButton);
            Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.cancelButton]));
            w3.X = 227;
            w3.Y = 114;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.okButton = new Gtk.Button();
            this.okButton.CanFocus = true;
            this.okButton.Name = "okButton";
            this.okButton.UseUnderline = true;
            this.okButton.Label = Mono.Unix.Catalog.GetString("Connect");
            this.serverPane.Add(this.okButton);
            Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.okButton]));
            w4.X = 113;
            w4.Y = 115;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.server = new Gtk.Entry();
            this.server.CanFocus = true;
            this.server.Name = "server";
            this.server.IsEditable = true;
            this.serverPane.Add(this.server);
            Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.server]));
            w5.X = 115;
            w5.Y = 16;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.port = new Gtk.Entry();
            this.port.CanFocus = true;
            this.port.Name = "port";
            this.port.Text = Mono.Unix.Catalog.GetString("6112");
            this.port.IsEditable = true;
            this.serverPane.Add(this.port);
            Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.port]));
            w6.X = 115;
            w6.Y = 49;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.lblNickname = new Gtk.Label();
            this.lblNickname.Name = "lblNickname";
            this.lblNickname.LabelProp = Mono.Unix.Catalog.GetString("Nickname:");
            this.serverPane.Add(this.lblNickname);
            Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.lblNickname]));
            w7.X = 20;
            w7.Y = 88;
            // Container child serverPane.Gtk.Fixed+FixedChild
            this.lblPort = new Gtk.Label();
            this.lblPort.Name = "lblPort";
            this.lblPort.LabelProp = Mono.Unix.Catalog.GetString("Port:");
            this.serverPane.Add(this.lblPort);
            Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.serverPane[this.lblPort]));
            w8.X = 22;
            w8.Y = 50;
            this.Add(this.serverPane);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 307;
            this.DefaultHeight = 185;
            this.Show();
            this.okButton.Clicked += new System.EventHandler(this.OnOkButtonClicked);
        }
    }
}
