// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GablarskiGtk {
    
    public partial class ConnectWindow {
        
        private Gtk.Table table;
        
        private Gtk.Button btnOk;
        
        private Gtk.Button button24;
        
        private Gtk.Entry entry1;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry entry3;
        
        private Gtk.Label lblNickname;
        
        private Gtk.Label lblPort;
        
        private Gtk.Label lblServer;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GablarskiGtk.ConnectWindow
            this.Name = "GablarskiGtk.ConnectWindow";
            this.Title = Mono.Unix.Catalog.GetString("Connect");
            this.Icon = Gdk.Pixbuf.LoadFromResource("GablarskiGtk.server_connect.png");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            // Container child GablarskiGtk.ConnectWindow.Gtk.Container+ContainerChild
            this.table = new Gtk.Table(((uint)(4)), ((uint)(3)), true);
            this.table.Name = "table";
            this.table.RowSpacing = ((uint)(6));
            this.table.ColumnSpacing = ((uint)(6));
            // Container child table.Gtk.Table+TableChild
            this.btnOk = new Gtk.Button();
            this.btnOk.CanFocus = true;
            this.btnOk.Name = "btnOk";
            this.btnOk.UseUnderline = true;
            this.btnOk.Label = Mono.Unix.Catalog.GetString("OK");
            this.table.Add(this.btnOk);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table[this.btnOk]));
            w1.TopAttach = ((uint)(3));
            w1.BottomAttach = ((uint)(4));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.button24 = new Gtk.Button();
            this.button24.CanFocus = true;
            this.button24.Name = "button24";
            this.button24.UseUnderline = true;
            this.button24.Label = Mono.Unix.Catalog.GetString("Cancel");
            this.table.Add(this.button24);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table[this.button24]));
            w2.TopAttach = ((uint)(3));
            w2.BottomAttach = ((uint)(4));
            w2.LeftAttach = ((uint)(2));
            w2.RightAttach = ((uint)(3));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.table.Add(this.entry1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table[this.entry1]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.entry2 = new Gtk.Entry();
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.Text = Mono.Unix.Catalog.GetString("6112");
            this.entry2.IsEditable = true;
            this.table.Add(this.entry2);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table[this.entry2]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.entry3 = new Gtk.Entry();
            this.entry3.CanFocus = true;
            this.entry3.Name = "entry3";
            this.entry3.IsEditable = true;
            this.table.Add(this.entry3);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table[this.entry3]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.lblNickname = new Gtk.Label();
            this.lblNickname.Name = "lblNickname";
            this.lblNickname.Xalign = 0F;
            this.lblNickname.LabelProp = Mono.Unix.Catalog.GetString("Nickname:");
            this.table.Add(this.lblNickname);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table[this.lblNickname]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.XPadding = ((uint)(5));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.lblPort = new Gtk.Label();
            this.lblPort.Name = "lblPort";
            this.lblPort.Xalign = 0F;
            this.lblPort.LabelProp = Mono.Unix.Catalog.GetString("Port:");
            this.table.Add(this.lblPort);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table[this.lblPort]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XPadding = ((uint)(5));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table.Gtk.Table+TableChild
            this.lblServer = new Gtk.Label();
            this.lblServer.Name = "lblServer";
            this.lblServer.Xalign = 0F;
            this.lblServer.LabelProp = Mono.Unix.Catalog.GetString("Server:");
            this.table.Add(this.lblServer);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table[this.lblServer]));
            w8.XPadding = ((uint)(5));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 262;
            this.DefaultHeight = 161;
            this.Show();
        }
    }
}
